// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package storage

import (
	"math"
	"sync"
	"time"
)

// WorkloadClass identifies the behavioral pattern of an active application workload.
type WorkloadClass int

const (
	// WorkloadClassUnknown indicates insufficient telemetry to classify the workload.
	WorkloadClassUnknown WorkloadClass = iota

	// WorkloadClassSmallRandomIO represents high-frequency sub-megabyte reads or writes
	// (e.g., 4KB-256KB random I/O, small file metadata, index lookups).
	WorkloadClassSmallRandomIO

	// WorkloadClassColumnarScan represents sparse, strided range reads across tabular files
	// (e.g., Apache Parquet, ORC, DuckDB / BigQuery external table scans).
	WorkloadClassColumnarScan

	// WorkloadClassStreamingSequential represents continuous high-speed sequential streaming
	// (e.g., AI/ML PyTorch DataLoaders, TFRecord reading, video transcoding).
	WorkloadClassStreamingSequential

	// WorkloadClassLargeCheckpoint represents massive multi-megabyte / multi-gigabyte atomic writes
	// (e.g., Orbax, JAX, PyTorch distributed model checkpoints).
	WorkloadClassLargeCheckpoint
)

func (w WorkloadClass) String() string {
	switch w {
	case WorkloadClassSmallRandomIO:
		return "SmallRandomIO"
	case WorkloadClassColumnarScan:
		return "ColumnarScan"
	case WorkloadClassStreamingSequential:
		return "StreamingSequential"
	case WorkloadClassLargeCheckpoint:
		return "LargeCheckpoint"
	default:
		return "AdaptiveAuto"
	}
}

// PrefetchStrategy defines how the reader should fetch data ahead of consumer reads.
type PrefetchStrategy int

const (
	// PrefetchStrategyDisabled stops prefetching completely when telemetry shows low cache hit rates.
	PrefetchStrategyDisabled PrefetchStrategy = iota

	// PrefetchStrategyMicroRange fetches small 256KB-1MB blocks on-demand with depth 1.
	PrefetchStrategyMicroRange

	// PrefetchStrategyPredictiveStrided fetches periodically spaced blocks based on detected seek stride.
	PrefetchStrategyPredictiveStrided

	// PrefetchStrategyAggressiveSequential scales chunk sizes from 8MB to 64MB with lookahead depth 2-4.
	PrefetchStrategyAggressiveSequential
)

func (s PrefetchStrategy) String() string {
	switch s {
	case PrefetchStrategyDisabled:
		return "Disabled"
	case PrefetchStrategyMicroRange:
		return "MicroRange"
	case PrefetchStrategyPredictiveStrided:
		return "PredictiveStrided"
	case PrefetchStrategyAggressiveSequential:
		return "AggressiveSequential"
	default:
		return "Auto"
	}
}

// UploadPolicy contains optimal transport and chunking decisions generated by the AI agent.
type UploadPolicy struct {
	ChunkSize      int
	PCUPartSize    int
	Concurrency    int
	DirectUpload   bool // Use direct media upload (bypassing resumable session) for small objects
	CoalesceWindow time.Duration
	FlushDeadline  time.Duration // Maximum time slow producer data can sit in buffer
}

// ReadPolicy contains optimal prefetching and lookahead decisions generated by the AI agent.
type ReadPolicy struct {
	Strategy         PrefetchStrategy
	InitialChunkSize int
	MaxChunkSize     int
	PrefetchDepth    int
	StrideBytes      int64
	IsSparse         bool
}

// AdaptiveAIAgent is an embedded, lightweight online reinforcement learning and policy decision engine.
// It tracks runtime I/O telemetry (producer inflow velocity, sequentiality score, consumer starvation,
// wire bandwidth, prefetch cache hit vs discard ratios), classifies the workload pattern in real time (< 1 µs overhead),
// and generates dynamically tuned SDK parameters to maximize throughput and minimize tail latency.
type AdaptiveAIAgent struct {
	mu sync.RWMutex

	// Producer inflow telemetry (Write path)
	producerInflowMBpsEwma float64
	lastWriteTime          time.Time
	totalBytesWritten      int64

	// Consumer read telemetry (Read path)
	lastOffset                 int64
	sequentialCount            int
	totalSeeksCount            int
	starvationEvents           int
	totalRequests              int
	avgRequestSize             float64
	detectedStrideBytes        int64
	lastSeekJump               int64
	totalPrefetchBytesServed   int64
	totalPrefetchBytesDiscarded int64

	// Network link & wire velocity telemetry
	observedMBpsEwma  float64
	observedRTTMsEwma float64
	congestionEvents  int

	// Learned policy weights (Contextual Multi-Armed Bandit / Linear Model)
	rewardEwma float64
	guardrail  *MemoryGuardrail
}

var (
	globalAIAgentOnce sync.Once
	globalAIAgent     *AdaptiveAIAgent
)

// GetGlobalAIAgent returns the shared singleton Adaptive AI Agent.
func GetGlobalAIAgent() *AdaptiveAIAgent {
	globalAIAgentOnce.Do(func() {
		globalAIAgent = NewAdaptiveAIAgent(nil)
	})
	return globalAIAgent
}

// NewAdaptiveAIAgent creates an initialized Adaptive AI Agent.
func NewAdaptiveAIAgent(guardrail *MemoryGuardrail) *AdaptiveAIAgent {
	if guardrail == nil {
		guardrail = NewMemoryGuardrail(DefaultGlobalMemoryLimit)
	}
	return &AdaptiveAIAgent{
		producerInflowMBpsEwma: 50.0, // Default 50 MB/s
		lastOffset:             -1,
		avgRequestSize:         32 * 1024 * 1024,
		observedMBpsEwma:       50.0, // Initial network assumption 50 MB/s
		observedRTTMsEwma:      25.0, // Initial RTT assumption 25 ms
		guardrail:              guardrail,
	}
}

// RecordWriteInflow records how fast the caller application is feeding bytes into the Writer.
func (a *AdaptiveAIAgent) RecordWriteInflow(bytesWritten int, dt time.Duration) {
	if bytesWritten <= 0 {
		return
	}
	a.mu.Lock()
	defer a.mu.Unlock()

	a.totalBytesWritten += int64(bytesWritten)
	durSec := dt.Seconds()
	if durSec > 0.0001 {
		currInflowMBps := (float64(bytesWritten) / (1024 * 1024)) / durSec
		const alpha = 0.2
		a.producerInflowMBpsEwma = (alpha * currInflowMBps) + ((1 - alpha) * a.producerInflowMBpsEwma)
	}
}

// RecordRead records a completed read operation into the online telemetry state.
func (a *AdaptiveAIAgent) RecordRead(offset int64, length int64, duration time.Duration, isStarved bool) {
	if length <= 0 {
		return
	}
	a.mu.Lock()
	defer a.mu.Unlock()

	a.totalRequests++

	// Track sequentiality vs strided seeks
	if a.lastOffset >= 0 {
		if offset == a.lastOffset {
			a.sequentialCount++
		} else {
			a.totalSeeksCount++
			jump := offset - a.lastOffset
			if jump > 0 && jump == a.lastSeekJump {
				// Consistent stride detected!
				a.detectedStrideBytes = jump
			}
			a.lastSeekJump = jump
		}
	}
	a.lastOffset = offset + length

	// Track consumer starvation
	if isStarved {
		a.starvationEvents++
	}

	// Exponential Moving Averages (EMA) with alpha = 0.2
	const alpha = 0.2
	a.avgRequestSize = (alpha * float64(length)) + ((1 - alpha) * a.avgRequestSize)

	durSec := duration.Seconds()
	if durSec > 0.0001 {
		currMBps := (float64(length) / (1024 * 1024)) / durSec
		a.observedMBpsEwma = (alpha * currMBps) + ((1 - alpha) * a.observedMBpsEwma)
		rttMs := durSec * 1000.0
		a.observedRTTMsEwma = (alpha * rttMs) + ((1 - alpha) * a.observedRTTMsEwma)
	}
}

// RecordPrefetchFeedback records cache hits vs discarded unread bytes to evaluate if prefetch is helpful.
func (a *AdaptiveAIAgent) RecordPrefetchFeedback(bytesServed int64, bytesDiscarded int64, wasStarved bool) {
	a.mu.Lock()
	defer a.mu.Unlock()

	a.totalPrefetchBytesServed += bytesServed
	a.totalPrefetchBytesDiscarded += bytesDiscarded
	if wasStarved {
		a.starvationEvents++
	}
}

// RecordNetworkTransfer records network wire transfer velocity and congestion backoffs.
func (a *AdaptiveAIAgent) RecordNetworkTransfer(bytesTransferred int64, duration time.Duration, isRetry bool) {
	if bytesTransferred <= 0 {
		return
	}
	a.mu.Lock()
	defer a.mu.Unlock()

	const alpha = 0.2
	durSec := duration.Seconds()
	if durSec > 0.0001 {
		currMBps := (float64(bytesTransferred) / (1024 * 1024)) / durSec
		a.observedMBpsEwma = (alpha * currMBps) + ((1 - alpha) * a.observedMBpsEwma)
	}

	if isRetry {
		a.congestionEvents++
	}
}

// ClassifyWorkload computes the active WorkloadClass based on multi-dimensional telemetry features.
func (a *AdaptiveAIAgent) ClassifyWorkload(payloadSizeHint int64) WorkloadClass {
	a.mu.RLock()
	defer a.mu.RUnlock()

	// 1. Large Checkpoint Hint
	if payloadSizeHint >= 64*1024*1024 {
		return WorkloadClassLargeCheckpoint
	}
	if payloadSizeHint > 0 && payloadSizeHint <= 1*1024*1024 {
		return WorkloadClassSmallRandomIO
	}

	// 2. Sequentiality analysis
	totalTransfers := a.sequentialCount + a.totalSeeksCount
	var seqRatio float64
	if totalTransfers > 0 {
		seqRatio = float64(a.sequentialCount) / float64(totalTransfers)
	} else {
		seqRatio = 0.5 // Default neutral
	}

	// 3. Request size analysis
	avgSize := a.avgRequestSize

	switch {
	case avgSize < 512*1024 && seqRatio < 0.4:
		return WorkloadClassSmallRandomIO
	case avgSize <= 4*1024*1024 && seqRatio < 0.6:
		return WorkloadClassColumnarScan
	case seqRatio >= 0.6 || avgSize > 4*1024*1024:
		return WorkloadClassStreamingSequential
	default:
		return WorkloadClassStreamingSequential
	}
}

// PredictUploadPolicy balances Producer Inflow Rate, Network Bandwidth, and Guardrail Budgets.
func (a *AdaptiveAIAgent) PredictUploadPolicy(payloadSizeHint int64, memoryBudget int64) UploadPolicy {
	workload := a.ClassifyWorkload(payloadSizeHint)

	a.mu.RLock()
	bw := a.observedMBpsEwma
	inflow := a.producerInflowMBpsEwma
	congested := a.congestionEvents > 0
	a.mu.RUnlock()

	if memoryBudget <= 0 {
		memoryBudget = DefaultGlobalMemoryLimit
	}

	// Dynamic AIMD Backoff if network is congested
	if congested {
		bw = bw * 0.70
	}

	switch workload {
	case WorkloadClassSmallRandomIO:
		// For small payloads (<= 1MB), use small 256KB chunk to eliminate memory waste
		chunk := 256 * 1024
		if payloadSizeHint > 0 && payloadSizeHint < int64(chunk) {
			chunk = int(payloadSizeHint)
		}
		return UploadPolicy{
			ChunkSize:      chunk,
			PCUPartSize:    16 * 1024 * 1024,
			Concurrency:    8, // High concurrency for small file IOPS
			DirectUpload:   payloadSizeHint > 0 && payloadSizeHint <= 8*1024*1024,
			CoalesceWindow: 10 * time.Millisecond,
			FlushDeadline:  25 * time.Millisecond,
		}

	case WorkloadClassLargeCheckpoint:
		// Massive model checkpointing: size chunk to saturate Bandwidth-Delay Product (BDP)
		// Target 500ms network pipeline saturation: ChunkSize = BW * 0.5s
		bdpChunk := int(bw * 1024 * 1024 * 0.50)
		chunkSize := 32 * 1024 * 1024
		if bdpChunk > chunkSize {
			chunkSize = bdpChunk
		}
		// Clamp to 64MB (or 128MB if large budget)
		maxChunk := 64 * 1024 * 1024
		if memoryBudget >= 512*1024*1024 {
			maxChunk = 128 * 1024 * 1024
		}
		if chunkSize > maxChunk {
			chunkSize = maxChunk
		}
		chunkSize = (chunkSize / (256 * 1024)) * (256 * 1024)

		pcuPart, pcuWorkers := CalculateDynamicPCUConfig(payloadSizeHint, bw, memoryBudget)

		return UploadPolicy{
			ChunkSize:      chunkSize,
			PCUPartSize:    pcuPart,
			Concurrency:    pcuWorkers,
			DirectUpload:   false,
			CoalesceWindow: 0,
			FlushDeadline:  100 * time.Millisecond,
		}

	default: // StreamingSequential / Standard
		// Producer-velocity aware chunk sizing:
		// If application produces slowly (< 10 MB/s), use 4MB chunk so data isn't stalled in RAM.
		chunkSize := 32 * 1024 * 1024
		flushDeadline := 50 * time.Millisecond
		if inflow > 0 && inflow < 15.0 {
			chunkSize = 4 * 1024 * 1024
			flushDeadline = 20 * time.Millisecond
		} else if payloadSizeHint > 0 && payloadSizeHint <= 32*1024*1024 {
			chunkSize = 16 * 1024 * 1024
		}

		return UploadPolicy{
			ChunkSize:      chunkSize,
			PCUPartSize:    64 * 1024 * 1024,
			Concurrency:    int(math.Max(4, math.Min(32, inflow/10))),
			DirectUpload:   false,
			CoalesceWindow: 5 * time.Millisecond,
			FlushDeadline:  flushDeadline,
		}
	}
}

// PredictReadPolicy evaluates prefetch effectiveness and adapts or disables prefetching.
func (a *AdaptiveAIAgent) PredictReadPolicy(totalSize int64, memoryBudget int64) ReadPolicy {
	a.mu.RLock()
	served := a.totalPrefetchBytesServed
	discarded := a.totalPrefetchBytesDiscarded
	starved := a.starvationEvents
	stride := a.detectedStrideBytes
	a.mu.RUnlock()

	workload := a.ClassifyWorkload(totalSize)

	if memoryBudget <= 0 {
		memoryBudget = DefaultGlobalMemoryLimit
	}

	// Calculate Prefetch Hit Ratio (Effectiveness)
	var hitRatio float64 = 1.0
	if totalBytes := served + discarded; totalBytes > 0 {
		hitRatio = float64(served) / float64(totalBytes)
	}

	// SELF-HEALING CONTROL: If prefetching is wasting > 60% of data, stop/disable prefetch!
	if (served+discarded) > 16*1024*1024 && hitRatio < 0.40 {
		return ReadPolicy{
			Strategy:         PrefetchStrategyDisabled,
			InitialChunkSize: 256 * 1024,
			MaxChunkSize:     512 * 1024,
			PrefetchDepth:    0, // Disable lookahead
			IsSparse:         true,
		}
	}

	// STRIDED ACCESS PATTERN: If periodic stride detected (Parquet column chunks)
	if stride > 0 && stride <= 16*1024*1024 {
		return ReadPolicy{
			Strategy:         PrefetchStrategyPredictiveStrided,
			InitialChunkSize: int(min(stride, 4*1024*1024)),
			MaxChunkSize:     4 * 1024 * 1024,
			PrefetchDepth:    2,
			StrideBytes:      stride,
			IsSparse:         true,
		}
	}

	switch workload {
	case WorkloadClassSmallRandomIO:
		return ReadPolicy{
			Strategy:         PrefetchStrategyMicroRange,
			InitialChunkSize: 256 * 1024,
			MaxChunkSize:     1 * 1024 * 1024,
			PrefetchDepth:    1,
			IsSparse:         true,
		}

	case WorkloadClassColumnarScan:
		return ReadPolicy{
			Strategy:         PrefetchStrategyMicroRange,
			InitialChunkSize: 1 * 1024 * 1024,
			MaxChunkSize:     4 * 1024 * 1024,
			PrefetchDepth:    2,
			IsSparse:         true,
		}

	case WorkloadClassStreamingSequential, WorkloadClassLargeCheckpoint:
		maxChunk := 64 * 1024 * 1024
		if memoryBudget >= 512*1024*1024 {
			maxChunk = 128 * 1024 * 1024
		}
		depth := 2
		if starved > 2 {
			depth = 4 // Expand depth to 4 if application experiences reader starvation
		}

		return ReadPolicy{
			Strategy:         PrefetchStrategyAggressiveSequential,
			InitialChunkSize: 8 * 1024 * 1024,
			MaxChunkSize:     maxChunk,
			PrefetchDepth:    depth,
			IsSparse:         false,
		}

	default:
		return ReadPolicy{
			Strategy:         PrefetchStrategyAggressiveSequential,
			InitialChunkSize: 8 * 1024 * 1024,
			MaxChunkSize:     32 * 1024 * 1024,
			PrefetchDepth:    2,
			IsSparse:         false,
		}
	}
}

// UpdateFeedback adjusts the internal policy reward based on measured throughput, latency, and memory.
func (a *AdaptiveAIAgent) UpdateFeedback(throughputMBps float64, p99LatencySec float64, memoryUsedMB float64) {
	a.mu.Lock()
	defer a.mu.Unlock()

	// Reward function: R = Throughput - (10 * P99Latency) - (0.01 * MemoryUsedMB)
	reward := throughputMBps - (10.0 * p99LatencySec) - (0.01 * memoryUsedMB)
	if math.IsNaN(reward) || math.IsInf(reward, 0) {
		return
	}

	const alpha = 0.1
	a.rewardEwma = (alpha * reward) + ((1 - alpha) * a.rewardEwma)
}

// GetMetricsSnapshot exposes the internal EWMA metrics for live dashboard plotting.
func (a *AdaptiveAIAgent) GetMetricsSnapshot() (inflow float64, net float64) {
	a.mu.RLock()
	defer a.mu.RUnlock()
	return a.producerInflowMBpsEwma, a.observedMBpsEwma
}
